enableGlobalCache: true

nodeLinker: pnp

packageExtensions:
  babel-plugin-relay@*:
    dependencies:
      "@babel/runtime": ^7.22.5
  local-pkg@*:
    dependencies:
      happy-dom: ^9.20.3

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.0.0-rc.46.cjs
